##' @title Add similarity flag value to a \code{simfit} object
##' 
##' @description Calculate the similarity between a single path generated by simfit and the
##' observed path used in the SSM fit. Similarity flag values are based on two interpretations
##' of the difference in distance and bearing between the two paths.
##' 
##' @param track a dataframe containing longitude and latitudes of the observed
##' path used in the SSM fit
##' @param sim_track a dataframe containing the longitude and latitude of a single 
##' simulated path from simfit
##' @param flag set to either 1 or 2 to define similarity index (see details)
##' 
##' @details
##' \code{flag = 1} will use an index based on Hazen (2017)\cr
##' \code{flag = 2} (the default) will use a custom index
##' 
##' @return a single value representing the similarity in distance and bearing between the two paths
##' 
##' @keywords internal
##' 
##' @importFrom sp spDistsN1
##' @importFrom geosphere bearing
##' @importFrom dplyr first last
##' 
##' @export
similarity_flag <- function(track, sim_track, flag = 2){
  
  dist_track <- spDistsN1(pts = cbind(first(track$lon), first(track$lat)),
                              pt = cbind(last(track$lon), last(track$lat)),
                              longlat = T)
  
  dist_sim <- spDistsN1(pts = cbind(first(sim_track$lon), first(sim_track$lat)),
                            pt = cbind(last(sim_track$lon), last(sim_track$lat)),
                            longlat = T)
  
  bear_track <- bearing(p1 = cbind(first(track$lon), first(track$lat)),
                                   p2 = cbind(last(track$lon), last(track$lat)))
  
  bear_sim <- bearing(p1 = cbind(first(sim_track$lon), first(sim_track$lat)),
                                 p2 = cbind(last(sim_track$lon), last(sim_track$lat)))
  
  if(flag == 1) {
    return(2 * (dist_track - dist_sim) / dist_track + (bear_track - bear_sim) / 90)
  } else {
    return(((dist_track - dist_sim) / dist_track) + ((bear_track - bear_sim) / bear_track))
  }

}

