##' @title Re-route a movement path around land using \code{pathroutr}
##'
##' @description A wrapper function that uses the `pathroutr` package to re-route
##' movement paths that cross a land barrier. The current implementation will take either
##' the output from a `fit_ssm` model or the simulations generated by `simfit`.
##'  
##' @param x either a \code{fG_ssm} model object or
##' a \code{fG_simfit} object containing simulated paths
##' @param what if using a \code{fG_ssm} object should the fitted (typically irregular in time) 
##' or predicted (typically regular in time) locations be re-routed
##' 
##' @details
##' When the input is a \code{fG_ssm} object `route_path` returns a `tibble` 
##' with the same dimensions as either the fitted or predicted locations. When 
##' the input is a \code{fG_simfit} object then `route_path` returns the same object
##' but with the locations within each simulation re-routed.
##' 
##' @references
##' Josh M. London. (2020) pathroutr: An R Package for (Re-)Routing Paths Around Barriers (Version v0.2.1)
##' \url{https://doi.org/10.5281/zenodo.4321827}
##' 
##' @examples 
##' fit <- fit_ssm(sese, vmax = 4, model = "crw", time.step = 24)
##' rrt_preds <- route_path(fit, what = "predicted")
##' 
##' trs <- simfit(fit, what = "predicted", reps = 5)
##' rrt_sims <- route_path(trs)
##' 
##' @importFrom purrr map_df
##' @importFrom dplyr group_by ungroup
##' @importFrom tidyr nest unnest
##' @importFrom sf st_as_sf st_transform st_make_valid st_buffer st_union 
##' @importFrom sf st_convex_hull st_intersection st_collection_extract st_sf 
##' @importFrom sf st_coordinates st_drop_geometry
##' @importFrom rnaturalearth ne_countries
##' @importFrom dplyr nest_by rowwise select
##' 
##' @export

route_path <- 
  function(x,
           what = c("fitted", "predicted")){
    
    if (!requireNamespace("pathroutr", quietly = TRUE)) {
      stop(
        cat("\n pathroutr pkg is not installed, use remotes::install_github(\"jmlondon/pathroutr\") to use this function\n")
      )
    }
    
    # what to do with the error information if the location is being moved by pathroutr...?
    
    what <- match.arg(what)
    
    if(!inherits(x, c("fG_ssm", "fG_simfit")))
    stop("x must be either a foieGras ssm fit object with class `fG_ssm`
         or a `fG_simfit` object containing the paths simulated from a `fG_ssm` fit object")
    
    if(inherits(x, "fG_ssm")) {
      # unnest foieGras ssm object
      df <- x %>% grab(what)
    
      # this should be trimmed to reduce computation time
      # base the trimming on the trs data
      df_sf <- df %>% 
        st_as_sf(coords = c("lon", "lat"), crs = 4326) %>% 
        st_transform(crs = 3857)
    
      # pathroutr needs a land shapefile to create a visibility graph from
      world_mc <- ne_countries(scale = "medium", returnclass = "sf") %>%
        st_transform(crs = 3857) %>%
        st_make_valid()
    
      land_region <- st_buffer(df_sf, dist = 50000) %>% 
        st_union() %>% 
        st_convex_hull() %>% 
        st_intersection(world_mc) %>% 
        st_collection_extract('POLYGON') %>% 
        st_sf()
    
      # create visibility graph
      vis_graph <- pathroutr::prt_visgraph(land_region)
      
      # create nested tibble grouped by individual track
      # use rowwise to process each row in turn
      df_rrt <- df_sf %>% 
        nest_by(id) %>%
        dplyr::rowwise() %>%
        mutate(pts = list(data %>% pathroutr::prt_trim(land_region)),
               rrt_pts = list(pathroutr::prt_reroute(pts, land_region, vis_graph)),
               pts_fix = list(pathroutr::prt_update_points(rrt_pts, pts)))
    
      # pull the corrected points from the object and reformat for foieGras
      df_rrt <- df_rrt %>%
        dplyr::select(id, pts_fix) %>%
        mutate(pts_fix = list(pts_fix %>% st_transform(crs = 4326) %>%
                              mutate(lon = st_coordinates(.)[,1],
                                     lat = st_coordinates(.)[,2]) %>%
                                st_drop_geometry() %>%
                                dplyr::select(date, lon, lat, x, y)))
    
      # remove nesting by individual path
      df_rrt <- df_rrt %>% unnest(cols = c(pts_fix))
    
      # append original columns to the tibble before nesting and outputting...
      # df_rrt <- df_rrt %>% left_join(df)
    
      # if fitted to fit_ssm object don't renest
      
    } else if (inherits(x, "fG_simfit")) {
      
    # unnest foieGras simfit object
    df <- x %>% unnest(cols = c(sims))
    
    # this should be trimmed to reduce computation time
    # base the trimming on the trs data
    df_sf <- df %>% 
      st_as_sf(coords = c("lon", "lat"), crs = 4326) %>% 
      st_transform(crs = 3857)
    
    # pathroutr needs a land shapefile to create a visibility graph from
    world_mc <- ne_countries(scale = "medium", returnclass = "sf") %>%
      st_transform(crs = 3857) %>%
      st_make_valid()
    
    land_region <- st_buffer(df_sf, dist = 50000) %>% 
      st_union() %>% 
      st_convex_hull() %>% 
      st_intersection(world_mc) %>% 
      st_collection_extract('POLYGON') %>% 
      st_sf()
    
    # create visibility graph
    vis_graph <- pathroutr::prt_visgraph(land_region)

    # create nested tibble grouped by individual track
    # use rowwise to process each row in turn
    df_rrt <- df_sf %>% 
      nest_by(id, rep) %>%
      dplyr::rowwise() %>%
      mutate(pts = list(data %>% pathroutr::prt_trim(land_region)),
             rrt_pts = list(pathroutr::prt_reroute(pts, land_region, vis_graph)),
             pts_fix = list(pathroutr::prt_update_points(rrt_pts, pts)))
    
    # pull the corrected points from the object and reformat for foieGras
    df_rrt <- df_rrt %>%
      dplyr::select(id, rep, pts_fix) %>%
      mutate(pts_fix = list(pts_fix %>% st_transform(crs = 4326) %>%
                            mutate(lon = st_coordinates(.)[,1],
                                   lat = st_coordinates(.)[,2]) %>%
                            st_drop_geometry() %>%
                            dplyr::select(model, date, lon, lat, x, y)))
    
    # remove nesting by individual path
    df_rrt <- df_rrt %>% unnest(cols = c(pts_fix))
    
    # format to foieGras object - including nexting by animal id
    df_rrt <- df_rrt %>% nest(sims = c(rep, date, lon, lat, x, y))
    class(df_rrt) <- append("fG_rws", class(df_rrt))
    class(df_rrt) <- append("fG_simfit", class(df_rrt))
    }
    
    return(df_rrt)
  }


