##' @title Filter \code{simfit} simulations
##' 
##' @description This function calculates the similarity between the simulations
##' generated by \code{simfit} and the observed path used in the \code{fG_ssm} fit,
##' and returns a \code{simfit} object containing the most similar tracks based on
##' a user specified quantile.
##' 
##' @param trs a \code{simfit} object
##' @param keep the quantile of flag values to retain
##' @param flag the similarity flag method (see \code{?simlarity_flag} for details)
##' 
##' @return a \code{simfit} object containing the filtered paths
##' 
##' @seealso \code{\link{similarity_flag}}
##' 
##' @examples
##' ## fit crw model to Argos LS data
##' fit <- fit_ssm(sese1, vmax = 4, model = "crw", time.step = 24)
##' 
##' ## generate 10 simulated paths from ssm fit
##' trs <- simfit(fit, what = "predicted", reps = 10)
##' 
##' ## filter simulations and keep paths in top 25% of flag values
##' trs_f <- sim_filter(trs, keep = .25, flag = 2)
##' plot(trs_f)

##' @importFrom dplyr group_by ungroup select "%>%" filter
##' @importFrom tidyr nest unnest
##' @importFrom stats quantile
##' @export
sim_filter <- function(trs, keep = .25, flag = 2){

  # filter based on similarity to original path
  # apply the similarity flag function to each simulated track
  # unnest the simfit object to extract the simulations
  trs_df <- trs %>% unnest(cols = c(sims))
  
  # can't figure out a map-type way to do this...
  # loop instead?
  trs_df$flg <- NA
  for (i in 1:length(unique(trs_df$id))){
    
    foo <- trs_df %>% filter(id == unique(trs_df$id)[i])
    
    if (requireNamespace("purrr", quietly = TRUE)) {
      foo <- purrr::map_df(split(foo, foo$rep),
                           function(.x) {
                             .x["flg"] <- similarity_flag(
                               track = foo %>% filter(rep == 0),
                               sim_track = .x,
                               flag = flag
                             )
                             .x
                           })
    } else {
      foo <- lapply(split(foo, foo$rep), function(.x) {
        .x["flg"] <- similarity_flag(
          track = foo %>% filter(rep == 0),
          sim_track = .x,
          flag = flag
        )
        .x
      }) %>%
        do.call(rbind, .)
    }
    trs_df$flg[trs_df$id == unique(trs_df$id)[i]] <- foo$flg
  }
  
  # filter based on user defined 'keep'
  # flag values can be positive or negative but will be centered around 0 (perfect match)
  # select only those tracks that have a flag value in the top 'keep' of flag values
  trs_df <- trs_df %>%
    group_by(id) %>%
    filter(abs(flg) < quantile(abs(flg), keep)) %>%
    ungroup()
  
  # format for foieGras output
  trs_filt <- trs_df %>% select(-flg) %>% nest(sims = c(rep, date, lon, lat, x, y)) # drop flag column
  class(trs_filt) <- append("fG_rws", class(trs_filt))
  class(trs_filt) <- append("fG_simfit", class(trs_filt))
  return(trs_filt)
}
